### ISSUE TITLE
Plugin for before you leave page

### ISSUE THREAD

**Issue by WillGross** [WillGross/STARRS#28]
This plugin has three text areas and two pairs of radio buttons
text 1 is milage finish
text 2 is fillup gallons
radio 1 is oil status (buttons for ok and low)
radio 2 is antifreeze status (buttons for ok and low)
text 3 is a comment box

on submit, the plugin retrieves the data logged in cookies from the before you drive plugin (namely the vehicle, mileage start and shift id) and creates an entry in the shift info table with this information. the entry in the vehicles table corresponding to the logged vehicle is then modified to reflect the new ending mileage, the oil status, and the antifreeze status. the plugin then forwards the user to the end of shift page.

**Comment by phanssen** [comment]
Called this complete driving
